DATA:
  data_name: s3dis
  data_root: ./data/S3DIS/Stanford3dDataset_v1.2_Aligned_Version/blocks_bs1_s1/data  # Fill in the pre-processed data path (which contains the .npy files)
  classes: 13
  fea_dim: 6
  voxel_size: 0.02
  voxel_max: 20480
  loop: 1
  cvfold: 0

TRAIN:
  #arch
  arch: stratified_transformer
  stem_transformer: True
  use_xyz: True
  sync_bn: False  # adopt sync_bn or not
  rel_query: True
  rel_key: True
  rel_value: True
  quant_size: 0.01
  downsample_scale: 8
  num_layers: 4 
  patch_size: 1 
  window_size: 4
  depths: [2, 2, 6, 2] 
  channels: [48, 96, 192, 384] 
  num_heads: [3, 6, 12, 24] 
  up_k: 3
  drop_path_rate: 0.3
  concat_xyz: True
  grid_size: 0.04
  max_batch_points: 140000
  max_num_neighbors: 34 # For KPConv
  ratio: 0.25
  k: 16

  # training
  aug: True
  transformer_lr_scale: 0.1
  jitter_sigma: 0.005
  jitter_clip: 0.02
  scheduler_update: epoch 
  scheduler: MultiStep 
  warmup: linear
  warmup_iters: 1500
  warmup_ratio: 0.000001
  use_amp: False
  optimizer: AdamW 
  ignore_label: 255
  train_gpu: [4,5,6,7]
  workers: 16  # data loader workers
  base_lr: 0.00005
  epochs: 100
  start_epoch: 0
  step_epoch: 30
  multiplier: 0.1
  momentum: 0.9
  weight_decay: 0.01
  drop_rate: 0.5
  manual_seed: 123
  # manual_seed:
  print_freq: 1
  save_freq: 1
  save_path: ./s3dis/fold0/2way5shot/flashattention2 # Fill the path to store the trained model
  weight: /home/sfpeng/COSeg-copy11/s3dis/fold0/2way5shot/flashattention/model/model_best.pth #/home/sfpeng/s3dis/fold0/1way5shot/model_best57_73.pth #./s3dis/fold0/1way5shot/flashattention2/model/model_best.pth #s3dis/fold0/2way1shot/flashattention/model_best.pth #s3dis/fold0/2way1shot/flashattention/model_best.pth #s3dis/fold0/2way1shot/flashattention/model/model_best.pth #./s3dis/fold1/1way1shot/flashattention/model/model_best.pth #./s3dis/fold0/1way1shot/flashattention/model/model_best.pth #./s3dis/fold0/slotattniter2num1/1way1shot/model/model_best.pth #./s3dis/fold0/globalquery_cluster1/1way1shot/model/model_best.pth #./s3dis/fold0/proposals_cut_seed1024_iou_0.8_nms_0.3/1way1shot/model/model_best.pth #./debug/s3dis/fold0/proposals_cut_seed1024_iou_0.8_nms_0.3/1way1shot/model/model_best.pth #./s3dis/fold0/querytoprototype/1way1shot/model/model_best.pth #./s3dis/fold0/withoutbpc/1way1shot/model/model_best.pth #s3dis/fold0/baselinesam/1way1shot/model_best.pth #s3dis/fold0/dpcfps/1way1shot/model/model_best.pth  # path to initial weight (default: none)
  resume: #./s3dis/fold0/ccc2/1way1shot/model/model_last.pth #s3dis/fold0/dpc/1way1shot/model/model_last.pth # path to latest checkpoint (default: none)
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 1

Few-shot:
  num_episode: 400
  n_way: 2
  k_shot: 5
  n_queries: 1
  ratio_dpc: 0.5
  num_clustering: 1
  residual: True
  num_episode_per_comb: 100
  pretrain_backbone: ../pretrained_model/s3_s0pre
  ckpt: ../pretrained_model/model.safetensors
  n_subprototypes: 100
  vis: 0
  forvis: 0
  vis_save_path: ./vis
  target_class: chair

Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

TEST:
  test: True
  eval_split: test # split for eval in [val or test], should be set to 'test' if test is True



